### ISSUE TITLE
Starting killrvideo throws `error: Error while calling service killrvideo.video_catalog.VideoCatalogService Error`

### ISSUE THREAD

**Issue by looselytyped** [KillrVideo/killrvideo-nodejs#7]
I followed the instructions listed [here](https://killrvideo.github.io/docs/languages/nodejs/) including setting memory to `4GB`; however I see this in `docker logs -f killrvideo_web_1` 

```
2017-02-08T15:10:30.460Z - error: Error while calling service killrvideo.video_catalog.VideoCatalogService Error
    at ServiceNotFoundError.ExtendableError (/opt/killrvideo-web/dist/server/utils/extendable-error.js:13:18)
    at ServiceNotFoundError (/opt/killrvideo-web/dist/server/utils/lookup-service.js:20:5)
    at tap.catch.err (/opt/killrvideo-web/dist/server/utils/lookup-service.js:35:13)
    at tryCatcher (/opt/killrvideo-web/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/killrvideo-web/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/opt/killrvideo-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/opt/killrvideo-web/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/killrvideo-web/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/opt/killrvideo-web/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

## Environment info 
Running [Docker for Mac](https://docs.docker.com/docker-for-mac/)

```
docker -v
Docker version 1.13.1-rc2, build 54f71fd
```

```
docker-compose -v
docker-compose version 1.11.0-rc1, build 0ea24e7
```

```
node -v
v6.2.2
```

```
npm -v
3.9.5
```

Full `docker logs -f killrvideo_web_1`

```
docker logs -f killrvideo_web_1
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
2017-02-08T15:08:44.653Z - verbose: Logging initialized at verbose
2017-02-08T15:08:44.655Z - info: Trying to start KillrVideo Web Server
2017-02-08T15:08:44.656Z - verbose: Looking up service cassandra
2017-02-08T15:08:44.656Z - verbose: Using etcd endpoint http://etcd:2379/v2/keys/killrvideo
2017-02-08T15:08:44.676Z - verbose: Found service cassandra at ["10.0.75.1:9042"] in etcd
2017-02-08T15:08:56.717Z - verbose: Could not initialize Cassandra keyspace. Retry 1 in 10000ms.
2017-02-08T15:09:06.729Z - verbose: Looking up service cassandra
2017-02-08T15:09:06.734Z - verbose: Found service cassandra at ["10.0.75.1:9042"] in etcd
2017-02-08T15:09:18.767Z - verbose: Could not initialize Cassandra keyspace. Retry 2 in 10000ms.
2017-02-08T15:09:28.771Z - verbose: Looking up service cassandra
2017-02-08T15:09:28.776Z - verbose: Found service cassandra at ["10.0.75.1:9042"] in etcd
2017-02-08T15:09:29.261Z - verbose: Looking up service cassandra
2017-02-08T15:09:29.264Z - verbose: Found service cassandra at ["10.0.75.1:9042"] in etcd
2017-02-08T15:09:30.710Z - info: KillrVideo Web Server listening on %j address=::, family=IPv6, port=3000
2017-02-08T15:10:30.454Z - verbose: Looking up service VideoCatalogService
2017-02-08T15:10:30.459Z - error: Error while calling service killrvideo.video_catalog.VideoCatalogService Error
    at ServiceNotFoundError.ExtendableError (/opt/killrvideo-web/dist/server/utils/extendable-error.js:13:18)
    at ServiceNotFoundError (/opt/killrvideo-web/dist/server/utils/lookup-service.js:20:5)
    at tap.catch.err (/opt/killrvideo-web/dist/server/utils/lookup-service.js:35:13)
    at tryCatcher (/opt/killrvideo-web/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/killrvideo-web/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/opt/killrvideo-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/killrvideo-web/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/opt/killrvideo-web/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/killrvideo-web/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/opt/killrvideo-web/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

Please let me know if I missed something obvious, or if there are any other bits of information that I can provide you with.

Thank you!

**Comment by jstafford** [comment]
I ran into this same problem as well. After spending a ridiculous amount of time debugging this, it appears that you must be using grpc version 1.0.0 (as specified in the npm-shrinkwrap.json file). Problem is that grpc@1.0.0 isn't prebuilt for current node environments (I'm using node 8.9.0), and when it tries to build from source grpc@1.0.0 won't compile properly for node 8.9.0.

As a quick hack to fix this, I installed node 4, and then was able to run 'npm install' successfully, and the app worked as expected.

The real fix is to remove all references to service.name, and pass the service name a different way, since that field is no longer set with current versions of protobufjs (which is called from grpc).

One possible fix is to explicitly set service.name in src/services/common/load.js.

An alternate fix would be to find a way to use the Google Cloud API yaml config files (see https://cloud.google.com/endpoints/docs/grpc/grpc-service-config) and then add the appropriate yaml for each service.
